parser: "babel-eslint"

env:
  browser: true
  commonjs: true

extends:
- airbnb

rules:
  brace-style: [2, "1tbs", { "allowSingleLine": true }]
  no-nested-ternary: 0
  newline-per-chained-call: ["error", { "ignoreChainWithDepth": 4 }]
